-- AlterTable
ALTER TABLE "BmsLogger" ALTER COLUMN "warningFlag" SET DATA TYPE VARCHAR[],
ALTER COLUMN "protectionFlag" SET DATA TYPE VARCHAR[],
ALTER COLUMN "faultStatus" SET DATA TYPE VARCHAR[],
ALTER COLUMN "errorMessages" SET DATA TYPE VARCHAR[];
